version: 5.1.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/logo.png
    manifest:
        name: William Mou Blog
        short_name: William Mou
        start_url: https://william-mou.github.io/
        theme_color: '#3273dc'
        background_color: '#3273dc'
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/William-Mou
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-sourcetree
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: facebook
donates:
    -
        type: wechat
        qrcode: img/wechat.jpg
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=619fa9250255320019654888&product=inline-share-buttons
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: William Mou
        author_title: HPC engineer
        location: NTHU CS, Taiwan
        avatar: img/me.jpeg
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/William-Mou
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/William-Mou
            Facebook:
                icon: fab fa-facebook
                url: https://www.facebook.com/william.mou1024/
            Telegram:
                icon: fab fa-telegram
                url: https://t.me/WilliamMou
            RSS:
                icon: fas fa-rss
                url: /
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            ASC: https://www.nthu.edu.tw/hotNews/content/1023
            PVE: https://sitcon.org/2020/agenda/bb4fc171-920f-48de-b411-ec0095306491
            SITCON: https://sitcon.org
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
    -
        position: left
        type: subscribe_email
        description: 
        feedburner_id: ''
    -
        position: left
        type: adsense
        client_id: ''
        slot_id: ''
    -
        position: left
        type: followit
        description: 
        action_url: ''
        verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
